name: cinemasy
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
#  ------------------------------------------------------------------------------------------
  connectivity_plus: ^4.0.1
  decorated_icon: ^1.2.1
  dio: ^4.0.6
  easy_localization: ^3.0.2
  flutter_bloc: ^8.1.3
  flutter_native_splash:
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.0
  go_router: ^7.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  overlay_support: ^2.1.0
  pretty_dio_logger: ^1.1.1
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_icon.png
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - pubspec.yaml